package resources.utility;

public class DataConstants {
	public static final String EmailSubjectLine = "email_subject_line";
	public static final String SelectListing = "select_listing";
	public static final String TitleHeader = "title_header";
	public static final String Group = "group";
	public static final String IndividualLead = "lead_email";
	public static final String SendTestEmailTo = "test_email";
	public static final String ScheduleDatePick = "schedule_date_picker";
	public static final String SelectTemplate = "select_template";
	public static final String Designation = "designation";
	public static final String Phone = "phone";
	public static final String Email = "email";
	public static final String Street = "street";
	public static final String City = "city";
	public static final String State = "state";
	public static final String Zip = "zip";
	public static final String Beds = "beds";
	public static final String Baths = "baths";
	public static final String Squarefeet = "square_feet";
	public static final String Zip_Criteria = "zip_criteria";
	public static final String Neighborhood = "neighborhood";
	public static final String SchoolDistrict = "school_district";
	public static final String County = "county";
	public static final String MinPrice = "minimum_price";
	public static final String MaxPrice = "maximum_price";
	public static final String Beds_Criteria = "beds_criteria";
	public static final String Baths_Criteria = "baths_criteria";
	public static final String Squarefeet_Criteria = "squarefeet_criteria";
	public static final String LotSize = "lot_size";
	public static final String Features = "features";
	public static final String Views = "views";
	public static final String Style = "style";
	public static final String PropertyTypes = "property_type";
	public static final String FirstName = "first_name";
	public static final String LastName = "last_name";
	public static final String Password = "password";
	public static final String ConfirmPassword = "confirm_password";
	public static final String AliasEmail = "alias_email";
}
